

services:
  mongo:
    image: mongo
    container_name: mongodb_chatapp
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: cagt-collab-app  # optional: name your container
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    command: sh -c "npm install && vite --host 0.0.0.0"

volumes:
  mongo-data:
